version: 1.0.{build}

image: Visual Studio 2017
# image: ubuntu

build_script:
  - dotnet build

environment:
  NUGET_API_KEY:
    secure: j9qYHISQiDQeJpRzdfWuEXtTrYBiKVGAC52jBTWP37BPjuKOtiUGj3/gKVVcWkln

deploy_script:
  - bash scripts/deploy.sh Cake.XmlConfigStructureBuilder/Cake.XmlConfigStructureBuilder.csproj

artifacts:
  - path: '*.nupkg'

after_deploy:
  - ps: Get-ChildItem *.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
